// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/protobuf/vault.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_protobuf_vault_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_vault_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_vault_proto_rawDescGZIP(), []int{0}
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	RecordType    string                 `protobuf:"bytes,2,opt,name=record_type,json=recordType,proto3" json:"record_type,omitempty"`
	Meta          string                 `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_internal_protobuf_vault_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_vault_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_vault_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Item) GetRecordType() string {
	if x != nil {
		return x.RecordType
	}
	return ""
}

func (x *Item) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

type AddDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDataRequest) Reset() {
	*x = AddDataRequest{}
	mi := &file_internal_protobuf_vault_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDataRequest) ProtoMessage() {}

func (x *AddDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_vault_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDataRequest.ProtoReflect.Descriptor instead.
func (*AddDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_vault_proto_rawDescGZIP(), []int{2}
}

func (x *AddDataRequest) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type AddDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDataResponse) Reset() {
	*x = AddDataResponse{}
	mi := &file_internal_protobuf_vault_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDataResponse) ProtoMessage() {}

func (x *AddDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_vault_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDataResponse.ProtoReflect.Descriptor instead.
func (*AddDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_vault_proto_rawDescGZIP(), []int{3}
}

type GetDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataRequest) Reset() {
	*x = GetDataRequest{}
	mi := &file_internal_protobuf_vault_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataRequest) ProtoMessage() {}

func (x *GetDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_vault_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataRequest.ProtoReflect.Descriptor instead.
func (*GetDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_vault_proto_rawDescGZIP(), []int{4}
}

func (x *GetDataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Item          *Item                  `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataResponse) Reset() {
	*x = GetDataResponse{}
	mi := &file_internal_protobuf_vault_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataResponse) ProtoMessage() {}

func (x *GetDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_vault_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataResponse.ProtoReflect.Descriptor instead.
func (*GetDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_vault_proto_rawDescGZIP(), []int{5}
}

func (x *GetDataResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetDataResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type DeleteDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDataRequest) Reset() {
	*x = DeleteDataRequest{}
	mi := &file_internal_protobuf_vault_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDataRequest) ProtoMessage() {}

func (x *DeleteDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_vault_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDataRequest.ProtoReflect.Descriptor instead.
func (*DeleteDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_vault_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteDataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDataResponse) Reset() {
	*x = DeleteDataResponse{}
	mi := &file_internal_protobuf_vault_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDataResponse) ProtoMessage() {}

func (x *DeleteDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_vault_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDataResponse.ProtoReflect.Descriptor instead.
func (*DeleteDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_vault_proto_rawDescGZIP(), []int{7}
}

type UpdateDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Meta          string                 `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDataRequest) Reset() {
	*x = UpdateDataRequest{}
	mi := &file_internal_protobuf_vault_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDataRequest) ProtoMessage() {}

func (x *UpdateDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_vault_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDataRequest.ProtoReflect.Descriptor instead.
func (*UpdateDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_vault_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateDataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDataRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpdateDataRequest) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

type UpdateDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDataResponse) Reset() {
	*x = UpdateDataResponse{}
	mi := &file_internal_protobuf_vault_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDataResponse) ProtoMessage() {}

func (x *UpdateDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_vault_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDataResponse.ProtoReflect.Descriptor instead.
func (*UpdateDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_vault_proto_rawDescGZIP(), []int{9}
}

type GetAllByTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordType    string                 `protobuf:"bytes,1,opt,name=record_type,json=recordType,proto3" json:"record_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllByTypeRequest) Reset() {
	*x = GetAllByTypeRequest{}
	mi := &file_internal_protobuf_vault_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllByTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllByTypeRequest) ProtoMessage() {}

func (x *GetAllByTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_vault_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllByTypeRequest.ProtoReflect.Descriptor instead.
func (*GetAllByTypeRequest) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_vault_proto_rawDescGZIP(), []int{10}
}

func (x *GetAllByTypeRequest) GetRecordType() string {
	if x != nil {
		return x.RecordType
	}
	return ""
}

type GetAllByTypeResponse struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Items         []*GetAllByTypeResponse_TypeItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllByTypeResponse) Reset() {
	*x = GetAllByTypeResponse{}
	mi := &file_internal_protobuf_vault_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllByTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllByTypeResponse) ProtoMessage() {}

func (x *GetAllByTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_vault_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllByTypeResponse.ProtoReflect.Descriptor instead.
func (*GetAllByTypeResponse) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_vault_proto_rawDescGZIP(), []int{11}
}

func (x *GetAllByTypeResponse) GetItems() []*GetAllByTypeResponse_TypeItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetAllByTypeResponse_TypeItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Meta          string                 `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllByTypeResponse_TypeItem) Reset() {
	*x = GetAllByTypeResponse_TypeItem{}
	mi := &file_internal_protobuf_vault_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllByTypeResponse_TypeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllByTypeResponse_TypeItem) ProtoMessage() {}

func (x *GetAllByTypeResponse_TypeItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_vault_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllByTypeResponse_TypeItem.ProtoReflect.Descriptor instead.
func (*GetAllByTypeResponse_TypeItem) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_vault_proto_rawDescGZIP(), []int{11, 0}
}

func (x *GetAllByTypeResponse_TypeItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetAllByTypeResponse_TypeItem) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

var File_internal_protobuf_vault_proto protoreflect.FileDescriptor

const file_internal_protobuf_vault_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/protobuf/vault.proto\x12\rgophkeeper.v1\"\a\n" +
	"\x05Empty\"O\n" +
	"\x04Item\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1f\n" +
	"\vrecord_type\x18\x02 \x01(\tR\n" +
	"recordType\x12\x12\n" +
	"\x04meta\x18\x03 \x01(\tR\x04meta\"9\n" +
	"\x0eAddDataRequest\x12'\n" +
	"\x04item\x18\x01 \x01(\v2\x13.gophkeeper.v1.ItemR\x04item\"\x11\n" +
	"\x0fAddDataResponse\" \n" +
	"\x0eGetDataRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"J\n" +
	"\x0fGetDataResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x04item\x18\x02 \x01(\v2\x13.gophkeeper.v1.ItemR\x04item\"#\n" +
	"\x11DeleteDataRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12DeleteDataResponse\"K\n" +
	"\x11UpdateDataRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x12\n" +
	"\x04meta\x18\x03 \x01(\tR\x04meta\"\x14\n" +
	"\x12UpdateDataResponse\"6\n" +
	"\x13GetAllByTypeRequest\x12\x1f\n" +
	"\vrecord_type\x18\x01 \x01(\tR\n" +
	"recordType\"\x8a\x01\n" +
	"\x14GetAllByTypeResponse\x12B\n" +
	"\x05items\x18\x01 \x03(\v2,.gophkeeper.v1.GetAllByTypeResponse.TypeItemR\x05items\x1a.\n" +
	"\bTypeItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04meta\x18\x02 \x01(\tR\x04meta2\xa1\x03\n" +
	"\fVaultService\x12H\n" +
	"\aAddData\x12\x1d.gophkeeper.v1.AddDataRequest\x1a\x1e.gophkeeper.v1.AddDataResponse\x12H\n" +
	"\aGetData\x12\x1d.gophkeeper.v1.GetDataRequest\x1a\x1e.gophkeeper.v1.GetDataResponse\x12Q\n" +
	"\n" +
	"DeleteData\x12 .gophkeeper.v1.DeleteDataRequest\x1a!.gophkeeper.v1.DeleteDataResponse\x12Q\n" +
	"\n" +
	"UpdateData\x12 .gophkeeper.v1.UpdateDataRequest\x1a!.gophkeeper.v1.UpdateDataResponse\x12W\n" +
	"\fGetAllByType\x12\".gophkeeper.v1.GetAllByTypeRequest\x1a#.gophkeeper.v1.GetAllByTypeResponseB7Z5github.com/msorokin-hash/passkeeper/internal/protobufb\x06proto3"

var (
	file_internal_protobuf_vault_proto_rawDescOnce sync.Once
	file_internal_protobuf_vault_proto_rawDescData []byte
)

func file_internal_protobuf_vault_proto_rawDescGZIP() []byte {
	file_internal_protobuf_vault_proto_rawDescOnce.Do(func() {
		file_internal_protobuf_vault_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protobuf_vault_proto_rawDesc), len(file_internal_protobuf_vault_proto_rawDesc)))
	})
	return file_internal_protobuf_vault_proto_rawDescData
}

var file_internal_protobuf_vault_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_internal_protobuf_vault_proto_goTypes = []any{
	(*Empty)(nil),                         // 0: gophkeeper.v1.Empty
	(*Item)(nil),                          // 1: gophkeeper.v1.Item
	(*AddDataRequest)(nil),                // 2: gophkeeper.v1.AddDataRequest
	(*AddDataResponse)(nil),               // 3: gophkeeper.v1.AddDataResponse
	(*GetDataRequest)(nil),                // 4: gophkeeper.v1.GetDataRequest
	(*GetDataResponse)(nil),               // 5: gophkeeper.v1.GetDataResponse
	(*DeleteDataRequest)(nil),             // 6: gophkeeper.v1.DeleteDataRequest
	(*DeleteDataResponse)(nil),            // 7: gophkeeper.v1.DeleteDataResponse
	(*UpdateDataRequest)(nil),             // 8: gophkeeper.v1.UpdateDataRequest
	(*UpdateDataResponse)(nil),            // 9: gophkeeper.v1.UpdateDataResponse
	(*GetAllByTypeRequest)(nil),           // 10: gophkeeper.v1.GetAllByTypeRequest
	(*GetAllByTypeResponse)(nil),          // 11: gophkeeper.v1.GetAllByTypeResponse
	(*GetAllByTypeResponse_TypeItem)(nil), // 12: gophkeeper.v1.GetAllByTypeResponse.TypeItem
}
var file_internal_protobuf_vault_proto_depIdxs = []int32{
	1,  // 0: gophkeeper.v1.AddDataRequest.item:type_name -> gophkeeper.v1.Item
	1,  // 1: gophkeeper.v1.GetDataResponse.item:type_name -> gophkeeper.v1.Item
	12, // 2: gophkeeper.v1.GetAllByTypeResponse.items:type_name -> gophkeeper.v1.GetAllByTypeResponse.TypeItem
	2,  // 3: gophkeeper.v1.VaultService.AddData:input_type -> gophkeeper.v1.AddDataRequest
	4,  // 4: gophkeeper.v1.VaultService.GetData:input_type -> gophkeeper.v1.GetDataRequest
	6,  // 5: gophkeeper.v1.VaultService.DeleteData:input_type -> gophkeeper.v1.DeleteDataRequest
	8,  // 6: gophkeeper.v1.VaultService.UpdateData:input_type -> gophkeeper.v1.UpdateDataRequest
	10, // 7: gophkeeper.v1.VaultService.GetAllByType:input_type -> gophkeeper.v1.GetAllByTypeRequest
	3,  // 8: gophkeeper.v1.VaultService.AddData:output_type -> gophkeeper.v1.AddDataResponse
	5,  // 9: gophkeeper.v1.VaultService.GetData:output_type -> gophkeeper.v1.GetDataResponse
	7,  // 10: gophkeeper.v1.VaultService.DeleteData:output_type -> gophkeeper.v1.DeleteDataResponse
	9,  // 11: gophkeeper.v1.VaultService.UpdateData:output_type -> gophkeeper.v1.UpdateDataResponse
	11, // 12: gophkeeper.v1.VaultService.GetAllByType:output_type -> gophkeeper.v1.GetAllByTypeResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_protobuf_vault_proto_init() }
func file_internal_protobuf_vault_proto_init() {
	if File_internal_protobuf_vault_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protobuf_vault_proto_rawDesc), len(file_internal_protobuf_vault_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protobuf_vault_proto_goTypes,
		DependencyIndexes: file_internal_protobuf_vault_proto_depIdxs,
		MessageInfos:      file_internal_protobuf_vault_proto_msgTypes,
	}.Build()
	File_internal_protobuf_vault_proto = out.File
	file_internal_protobuf_vault_proto_goTypes = nil
	file_internal_protobuf_vault_proto_depIdxs = nil
}
