name: Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: ["main"]
    paths-ignore:
      - "**/*.md"

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Go tests
    if: ${{ github.event.pull_request.base.ref == 'main' && !github.event.pull_request.draft }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.5"
          cache: true

      - name: Clean Go test cache
        run: go clean -testcache

      - name: Run tests
        run: go test ./... -count=1
